### ISSUE TITLE
settings dialog does not appear

### ISSUE THREAD

**Issue by nelsongc** [abynim/UserFlows.sketchplugin#105]
When I go to Settings.. options the dialog disappear immediately.
Ketch 47 (45396)

**Comment by deelydian** [comment]
Thank you so much for this plugin...it's going to be so valuable for my design work! I'm experiencing sort of the same thing as @nelsongc. When I click on Settings in the Plugin menu for User Flow in Sketch, the dialog never appears, or at least I am not seeing it appear on my screen. I do know that I saw the Settings one time, but I have not been able to get them to appear again. I am wanting to remove the outline around the links in my mockups, but I have no way to do so right now. Any ideas on what could be causing this?

**Comment by nelsongc** [comment]
to remove the outline I edit the plugin, in the folder of plugin drag in Atom app, go to
UserFlow.sketchplugin/Contents/Sketch/scripts.js

line 940, 1143, appears this code, the last value change from 1 to 0
showLinkRects = NSUserDefaults.standardUserDefaults().objectForKey(kShowsLinkRectsKey) || 1;

after change.
showLinkRects = NSUserDefaults.standardUserDefaults().objectForKey(kShowsLinkRectsKey) || 0;

**Comment by abynim** [comment]
This is fixed in v2.0.7 (#108). Please update!

**Comment by nelsongc** [comment]
Thank you very much for fixing it and adding the spanish language. 

muchas gracias!!

**Comment by deelydian** [comment]
Thank you so much for fixing this! I used your original response to successfully remove the borders, but this makes it much more user friendly =)
