### ISSUE TITLE
Sketch V 47.1 User Flow doesn't seem to work

### ISSUE THREAD

**Issue by alexandrequemin** [abynim/UserFlows.sketchplugin#109]
Sketch V 47.1 User Flow doesn't seem to work, please help me :)

**Comment by abynim** [comment]
@alexandrequemin what part of it is not working for you?

**Comment by alexandrequemin** [comment]
To add a path between an element and an artboard :(

**Comment by abynim** [comment]
It should still be working in v47.1 – Did you try the `Redraw Connections` command?

**Comment by alexandrequemin** [comment]
Thanks, it works :)

**Comment by abynim** [comment]
Awesome! Thanks for reporting back 👍
