### ISSUE TITLE
Plugin doesn't work with Sketch 48 update

### ISSUE THREAD

**Issue by yoyoadam** [abynim/UserFlows.sketchplugin#113]
Hey!

So upon updating to Sketch 48, the plugin has numerous issues.

First, Sketch have added the CMD, Shift K shortcut to 'Change Colour Profile' in the settings menu which overrides User Flows default 'Create Link' command. I know you can create your own shortcuts and change this, but just a heads up for future versions.

Secondly, generating a flow diagram causes Sketch 48 to crash every time for me.

If I can be of any more help please let me know.

Thanks,
Adam

**Comment by abynim** [comment]
Both these issues have been addressed in 2.0.8. Please get the latest version
