### ISSUE TITLE
User flow plugin doesn't work with Sketch version 48

### ISSUE THREAD

**Issue by cathux** [abynim/UserFlows.sketchplugin#115]

**Comment by abynim** [comment]
Please update to the latest version.

**Comment by cathux** [comment]
it's been updated to the latest version yesterday, that's the turning point
of User flow plugin stopped working. I am using version 47.1 version at
home, the plugin is working fine.

**Comment by abynim** [comment]
@cathux sorry, I meant please update to the latest version of the plugin. I fixed the plugin for Sketch 48 couple of days back. Let me know if it still doesn't work and I can reopen the issue.
