### ISSUE TITLE
Overwrite flow artboard

### ISSUE THREAD

**Issue by jberk-godaddy** [abynim/UserFlows.sketchplugin#118]
Since flows need to be constantly regenerated when changes are made, it would be nice if it overwrote the other flow artboard that it had created, instead of always making another one.

**Comment by jberk-godaddy** [comment]
No comment just closed?

**Comment by abynim** [comment]
Oops, didn't realize issues get closed automatically when mentioned in merge comments. I added the option to `Update Flow Diagram` in the latest update, which fixes this issue to some extent.

**Comment by jberk-godaddy** [comment]
oh ok cool thanks!



*Joshua Berk*

**Comment by garaujo-edumobi** [comment]
@abynim 
Congratulations on the plugin, it helps a lot.

I use Abstract to control the version of artboards and it is indicating that the artboard is being deleted and a new one is being created. This breaks the process of version control, which relies on an artboard to keep the commits organized.

Can you keep the current artboard object while running Update Flow Diagram, updating only the properties and objects within that artboard?
