### ISSUE TITLE
Generating flow diagram is no longer working

### ISSUE THREAD

**Issue by p-saovapakhiran** [abynim/UserFlows.sketchplugin#123]
Somehow when generating a flow diagram, it creates an empty page with the name "Page 3." I'm supposed to ship the flow diagram to my client, but now it's not working. Please help!

**Comment by abynim** [comment]
@p-saovapakhiran Are you using the latest version of the plugin? Can you please check Console.app to see if any errors are logged when you run the Generate Diagram command?

**Comment by abynim** [comment]
@p-saovapakhiran Also, what version of Sketch are you running?

**Comment by ghost** [comment]
I'm having the same trouble. When I "Generate Flow Diagram" and complete all the fields in the resulting "Generate a User Flow" dialogue, a new Sketch page is created but it's completely blank / empty.

I checked for User flow plugin updates and got the"You're good" message.

I'm running Sketch #49.3 (51167)

Thanks,
Tim

**Comment by ghost** [comment]
I don't know if this is any help - 

![image](https://user-images.githubusercontent.com/978182/38554702-82d14d40-3cbb-11e8-9d5c-66bb61ff97fa.png)

**Comment by melaniap** [comment]
Same here. I get  an empty page named **_Page 3_**. 
I'm running Sketch 49(51002) on Mac Os Sierra 10.12.6 and the Plugin is up to date.

I get this error
![schermata 2018-04-10 alle 14 19 35](https://user-images.githubusercontent.com/17333206/38556523-4860e47c-3cca-11e8-8e77-5235abfa4ae4.png)

**Comment by p-saovapakhiran** [comment]
@abynim I'm using Sketch version 49.3 (51167) and User Flows plugin version 2.1.1. Here are screenshots from the console:

<img width="1119" alt="screen shot 2018-04-10 at 21 13 45" src="https://user-images.githubusercontent.com/3438448/38562192-30e051ea-3d04-11e8-9878-f4ff1a34d1aa.png">
<img width="1119" alt="screen shot 2018-04-10 at 21 14 04" src="https://user-images.githubusercontent.com/3438448/38562197-33c8ab0a-3d04-11e8-9e10-d91485c8a190.png">

**Comment by p-saovapakhiran** [comment]
@abynim Also, in the new version, when links are created, they seem to get messy very quickly. Each link now points to the midpoint on the left edge of the destination artboard instead of the topmost point. This seems to make links crossing each other more often.

Here are the examples:

Previous version:
<img width="1280" alt="before" src="https://user-images.githubusercontent.com/3438448/38563086-444fef18-3d06-11e8-93ad-3b1018ccffd9.png">

New version:
<img width="1280" alt="after" src="https://user-images.githubusercontent.com/3438448/38563095-47d1b7b6-3d06-11e8-903b-16bb9b81d39a.png">

I think the previous one looks way more elegant.

I really hope we could have an option in the plugin settings to bring back the original presentation of links. I hope you could consider this.

Thank you for making and always supporting this awesome plugin, by the way.

**Comment by abynim** [comment]
Thanks for the details everyone. Looks like I introduced this bug when adding support for the new Sketch Prototype connections. Will fix this and push an update today 👍

**Comment by abynim** [comment]
@p-saovapakhiran the links pointing to the left mid-point of the destination artboard was added to match the native Sketch way of rendering flow connections. Switching back to the old style would create some edge-cases which I don't know how to handle at this point. So will have to keep that one for later.

**Comment by joaosimons** [comment]
hey @abynim great plugin. Are you fixing this issue soon?

**Comment by deniszakalinsky** [comment]
@abynim One of the best plugin ever. But still can't generate workflows, no any dialogs appears. Sketch 47.1.

**Comment by abynim** [comment]
The `newPageItemTitle` issue has been fixed in the latest update. Also added an `Artboard Magnets` option in Settings to point connections to either top-left corner or north/south/east/west points of the destination artboard.
@p-saovapakhiran @joaosimons @timtops @melaniap please let me know if the update fixes all the issues for you as well. Thanks for helping me debug this 👍

**Comment by p-saovapakhiran** [comment]
@abynim Thanks a lot! It's now working even better. 👍
