### ISSUE TITLE
User flow not working for Sketch version 49 (51167)

### ISSUE THREAD

**Issue by yuqicornell** [abynim/UserFlows.sketchplugin#127]
wondering if it is just me or everyone?

**Comment by abynim** [comment]
@yuqicornell are you running the latest version of the plugin? If yes, do share some more details about what is not working.

**Comment by yuqicornell** [comment]
Hi @abynim, 
I'm running v2.1.3 plugin, and sketch 50.2 (55047).
Please see the gif below. Is there's something I'm not using correctly?

Thanks so much!

![2018-05-18_09-28-15](https://user-images.githubusercontent.com/9273242/40237482-9867a6be-5a7e-11e8-8968-ba31d9cf1098.gif)

**Comment by abynim** [comment]
@yuqicornell for now the plugin only allows creating a link between a layer and an artboard. So it should work if you select a layer and the destination artboard before running the Create Link command. I'm considering adding the option to link two layers (not just layer and artboard) but it's not supported yet.

**Comment by yuqicornell** [comment]
Hi @abynim , thank you very much for the clarification! I look forward to it. :)

Thanks again for making this excellent plugin, I deeply appreciated it.
