### ISSUE TITLE
Cannot generate flow diagram in Sketch v51

### ISSUE THREAD

**Issue by claudiofrs** [abynim/UserFlows.sketchplugin#133]
Cannot generate flow diagram after Sketch update to v51. The connection is suddenly hidden when I press `Generate flow diagram`. At the previous version of Sketch, usually a new page was created (if you choose to, but it doesn't work either with existing page), and the flow was there.

**Comment by vincmac** [comment]
Same here,
And If you try to update an already existing flow it deletes the corresponding artboard and brings you back to the last page you were before the _flow page.

**Comment by abynim** [comment]
@claudiofrs  @vincmac – please try the updated version (2.1.4). These issues should be fixed for Sketch 51. Thanks for the reports 👍

**Comment by jshmllr** [comment]
Working now for me
