### ISSUE TITLE
Feature Request : Integrating with Sketch's built in prototyping tools. 

### ISSUE THREAD

**Issue by Raghav789** [abynim/UserFlows.sketchplugin#139]
It would awesome if it's possible.

**Comment by abynim** [comment]
Some insights into how you would use such a feature will be awesome. The plugin already supports the ability to include Sketch Prototyping links in an exported flow diagram. What's missing?

**Comment by Raghav789** [comment]
Okay sorry, I just checked it's already there before it had its own linking system.
