### ISSUE TITLE
UserFlows doesn't work on Sketch 4.xx

### ISSUE THREAD

**Issue by ghost** [abynim/UserFlows.sketchplugin#14]
Can't create user flow links with the latest version of Sketch 4.xx.
![screen shot 2016-12-01 at 11 29 47 am](https://cloud.githubusercontent.com/assets/1034468/20802280/97bd533a-b7b9-11e6-94fa-0e59aaa430f0.png)

**Comment by abynim** [comment]
To create a link you must select a layer and the destination artboard before running the command. It should work with Sketch 41.xx and above.

**Comment by ghost** [comment]
I followed exactly as your video. It doesn't work.

**Comment by abynim** [comment]
Is the destination artboard or link layer a Symbol? Also, please try restarting Sketch just to make sure it's not a problem with the selection context.

**Comment by ghost** [comment]
Yes, they're symbols. I have tried restarted sketch multiple times after I installed the plugin.

**Comment by abynim** [comment]
Does it work when Symbols are not involved? Could you please try it with a regular layer as a link and a regular artboard as the destination? Thanks for helping debug btw 👍

**Comment by ghost** [comment]
I have tried linking shapes, text, bmps, and layers. Nothing works.

**Comment by abynim** [comment]
Can you make a quick screencast of what you're doing? I have no other way to recreate the issue. It seems to be working for everyone else so far!

**Comment by ghost** [comment]
I can't do a screencast right now but here's a screenshot:
![sketch](https://cloud.githubusercontent.com/assets/1034468/20839795/e7a63c8c-b87b-11e6-837f-4127b6fed32e.png)

**Comment by abynim** [comment]
@kainproductions You can only link a layer to an artboard. In this screenshot you're trying to link a layer to another layer. That will not work. Select the grey rectangle, then select the second artboard, then run the command again.
