### ISSUE TITLE
Invisible Layers Crashing User Flows

### ISSUE THREAD

**Issue by mlaurita** [abynim/UserFlows.sketchplugin#146]
Hey Guys,

I sometimes have to create invisible "hotspots" using layers with no fill or stroke and linking them to artboards. I think these are causing user flows to regularly crash sketch. Can you guys fix this issue please?

**Comment by abynim** [comment]
@mlaurita not sure why that would crash Sketch. If it happens again please save a crash report and paste it in here. Also let me know what version of Sketch you're using.
