### ISSUE TITLE
Update Flow Diagram issue

### ISSUE THREAD

**Issue by garaujo-edumobi** [abynim/UserFlows.sketchplugin#149]
@abynim
Congratulations on the plugin, it helps a lot.

I use Abstract to control the version of artboards and it is indicating that the artboard is being deleted and a new one is being created when using the Update Flow Diagram feature. This breaks the process of version control, which relies on an artboard to keep the commits organized.

Can you keep the current artboard object while running Update Flow Diagram, updating only the properties and objects within that artboard?

**Comment by abynim** [comment]
Good call @garaujo-edumobi  👍 Thanks for reporting
I've fixed this in v2.3.2. Please test and let me know if it works as expected.

**Comment by garaujo-edumobi** [comment]
Good job, man. Worked perfectly. Really thanks for keeping this plugin.
