### ISSUE TITLE
plugin not working for sketch ver.3.6.1

### ISSUE THREAD

**Issue by dew90730** [abynim/UserFlows.sketchplugin#151]
both with clicking the menu(plugins>user flow>create links) and shortcuts, plugin does now work.
it doesn't create any links or even a pop-up.

**Comment by ghost** [comment]
Same problem.

**Comment by abynim** [comment]
Sorry guys, the latest Sketch version at this time is 52. It's difficult for me to maintain backwards compatibility all the way back to 36 😞
