### ISSUE TITLE
Sketch v52.3 + UserFlows v2.3.2 - Cannot Create Link

### ISSUE THREAD

**Issue by ghost** [abynim/UserFlows.sketchplugin#152]
Using the latest versions of Sketch (52.3) & UserFlows (2.3.2) I am unable to create a new UserFlow link. Each attempt results in the following error...

<img width="420" alt="screen shot 2018-11-12 at 2 08 23 pm" src="https://user-images.githubusercontent.com/1749958/48378044-72bf2080-e684-11e8-81f6-58fd8917fc3a.png">

I have reviewed any previous issues relating to this that have occurred in the last few months and am unable to resolve the problem. I have also removed and reinstalled the plugin and the issue persists. Any help would be appreciated.

**Comment by abynim** [comment]
@graemeasher this does not look like an error from UserFlows. Perhaps the shortcut has been taken over by a different plugin? Please confirm if you see the same message when running the command from the Plugins menu instead of using the shortcut.

**Comment by ghost** [comment]
I did get the exact same message when running from the plugins menu. Based on your feedback I disabled all additional plugins and UserFlow started working again. It ended up being the Diverse-UI plugin that was causing the issue. Thanks for the feedback.
