### ISSUE TITLE
Feature request: multiple connections from same link

### ISSUE THREAD

**Issue by airandfingers** [abynim/UserFlows.sketchplugin#154]
It'd also be nice to be able to add multiple links from a single element, e.g. Success and Error cases.

**Comment by abynim** [comment]
That is where `Conditions` come in. If you think about it, it is technically impossible for one link to point to multiple screens without some logic to divert it in the right direction. Conditions allow you to document this logic in your design itself. Here's your example in diagram form:
![conditional flow](https://user-images.githubusercontent.com/7082849/49322342-9c63bd00-f549-11e8-890f-faca4ce1403c.png)

**Comment by airandfingers** [comment]
Ah yes, after I posted this, a coworker showed me how conditions serve this purpose. Thanks for answering!
