### ISSUE TITLE
I cannot create a link

### ISSUE THREAD

**Issue by ghost** [abynim/UserFlows.sketchplugin#156]
Create link, Generate flow diagram does not work among several other buttons.

**Comment by abynim** [comment]
Let me know which version of Sketch you're running.

**Comment by ghost** [comment]
The version is 52.6

**Comment by abynim** [comment]
Can't seem to reproduce this issue. Does it happen with a specific document? Could you please share a screenshot of your UserFlows > Settings window? Perhaps it's a specific setting that's causing the issue. 
Thanks for reporting and following up btw 👍

**Comment by ghost** [comment]
Thank you for the plugin and assisting. 
The error I get is: Select a layer or group to define as a Link, select the destination artboard, then run this command again.

The settings are: (see attachment1
<img width="469" alt="attachment1" src="https://user-images.githubusercontent.com/12876549/51507045-3ed44a00-1def-11e9-8ea5-ccef72bd36e7.png">
)

I've installed (and uninstalled) probably more than 7 times already both manually and through runner. 
I select a artboard, then select a group and symbol and try to link them and it doesn't work. 
I've tried linking various things on various artboards and none have succeeded. 

Watched youtube videos to make sure I wasn't doing it wrong, and have been following the exact same steps as they are straightforward, yet no succes thus far. 

If I can help in anyway to clarify further, please let me know.

**Comment by ghost** [comment]
Also thought it might have to do with the sketch file itself. 
So I created a new sketch file, created on page1 (artboard) a rectangle and a triangle and trying to link them through the shortcut and through clicking on "create link" through the plugin section. 

No succes, see image
<img width="1680" alt="screenshot 2019-01-22 at 02 50 58" src="https://user-images.githubusercontent.com/12876549/51507299-96bf8080-1df0-11e9-9f69-aff29c871bd7.png">

**Comment by abynim** [comment]
To create a Link you must have only two items selected, one of them should be a layer/symbol/group and the second should be an artboard. Could you try running the `Create Link` command with only the group and artboard selected? 
Creating links between two layers is unfortunately not supported at this time.
Let me know if that works. I probably need a better error message there to make it clear.

**Comment by abynim** [comment]
> Also thought it might have to do with the sketch file itself.
> So I created a new sketch file, created on page1 (artboard) a rectangle and a triangle and trying to link them through the shortcut and through clicking on "create link" through the plugin section.
> 
> No succes, see image
> <img alt="screenshot 2019-01-22 at 02 50 58" width="1680" src="https://user-images.githubusercontent.com/12876549/51507299-96bf8080-1df0-11e9-9f69-aff29c871bd7.png">

Here you have two shapes selected. If one of them is an artboard it _should_ work.

**Comment by ghost** [comment]
You're right, it was my wrongdoing as I was not selecting a artboard. 
Thank you for clarifying. 

It works fine!
