### ISSUE TITLE
Can't generate in Sketch 53.1?

### ISSUE THREAD

**Issue by rdoyle720** [abynim/UserFlows.sketchplugin#162]
Updated to Sketch 53.1 this morning. Now when I use the Generate Flow Diagram option and click Generate Diagram, nothing happens.

**Comment by abynim** [comment]
@rdoyle720 thanks for reporting. Do you see any errors in Console.app when you click Generate Diagram?

**Comment by alvarotrapote** [comment]
Same problem here. I've got this error (from Console.app)
```
default	10:31:59.630397 +0000	Sketch	TypeError: undefined is not a function (near '...exportRequest.setBackgroundColor...')
line: 1002
sourceURL: /Users/alvarotrapote/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js
column: 35
stack: generateFlowWithSettings@/Users/alvarotrapote/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:1002:35
generateFlow@/Users/alvarotrapote/Library/Application Support/com.bohemiancoding.sketch3/Plugins/UserFlows.sketchplugin/Contents/Sketch/script.js:924:27
```

Thanks for this awesome plugin :)

**Comment by alvarotrapote** [comment]
By the way, as a workaround, commenting line 1002 from UserFlows.sketchplugin seems to solve the issue.

**Comment by abynim** [comment]
@alvarotrapote thank YOU for help with debugging! Fixed and updated 👍
@rdoyle720 hope the update fixes the issue for you as well. Please reopen the issue if that's not the case.
