### ISSUE TITLE
Sketch 57 - Generate Flow Diagram not working w/ existing Sketch prototyping links

### ISSUE THREAD

**Issue by ghost** [abynim/UserFlows.sketchplugin#167]
I am attempting to generate a flow diagram using the built-in Sketch App prototyping links, however when I **_select all artboards > Generate Flow Diagram_**, I only get a single artboard with a link in my new flow diagram page.

Sketch Version 57.1

**Comment by abynim** [comment]
Hi @nlourtsd. I can't seem to reproduce this.

By the way, you don't need to *select all artboards* first. You can run the *Generate Flow Diagram* command with nothing selected, then in the dialog you need to select the initial artboard of your flow. The plugin will automatically detect links originating from this initial artboard and generate a diagram from that point onwards.

If it's still not working, would you be able to share your document? That would be the fastest way to debug this.

**Comment by ghost** [comment]
> then in the dialog you need to select the initial artboard of your flow. The plugin will automatically detect links originating from this initial artboard and generate a diagram from that point onwards.

Thank you, selecting the initial artboard was key for successfully generating the flow diagram.

**Comment by abynim** [comment]
Thanks for confirming!
