### ISSUE TITLE
Generate Flow diagram does not generate complete flow

### ISSUE THREAD

**Issue by sanjaay** [abynim/UserFlows.sketchplugin#169]
Used with Sketch 60.1

When I create a flow with conditions, after connecting the flow and using "Generate Flow diagram" it does not generate the complete flow. It only generates part of the actual flow.

**Comment by joelandrewbrown** [comment]
Hey @sanjaay - I ran into this as well. It seems to only generate artboards that are in fact connected. If you have any artboards that aren't connected to the flow somehow they won't be generated! Hope this helps.

There have been times I "thought" everything was connected, but on further inspection I was missing something somewhere.

**Comment by parkerkuncl** [comment]
Unsubscribe 

--------------------
Parker Kuncl
323-459-0814

**Comment by abynim** [comment]
Correct. The plugin only traverses artboards that are connected starting from the Home artboard you select when generating a flow. There is no way for the plugin to know which other artboards you want to include in the flow.

Let me know if it's not generating complete flows even for artboards that are connected, that might be a bug. If you can link to a demo Sketch doc to help reproduce the issue I can get to it much faster. Thanks!
