### ISSUE TITLE
In a generated flow, the numbering seems odd

### ISSUE THREAD

**Issue by joelandrewbrown** [abynim/UserFlows.sketchplugin#170]
I organize my artboards in the layer palette, anyone have any ideas on how to keep the numbering of a generated flow in order of artboards in the layer palette? It seems to be random, but I'm likely just not understanding how it's supposed to work.

**Comment by abynim** [comment]
The numbering is based on how the screens are connected. It was mostly meant as a way to identify screens when presenting the flow over a call or when providing feedback over email (saying "Screen 4 has an issue" is easier than saying "6th screen from top has an issue").

I see how you might want your own numbering system though. Making numbering optional would help, maybe?

**Comment by joelandrewbrown** [comment]
Thanks for clarifying that! That makes sense. In my case, hiding the numbers and/or the option for the numbers to follow the sequence of the order of artboards in the layer palette (top to bottom) would be super helpful. I have 154 artboards with multiple connections all over the place so the order-of-flow sequence doesn't work well for me in this case.

**Comment by abynim** [comment]
Better late than never!
