### ISSUE TITLE
No links appear

### ISSUE THREAD

**Issue by gayco** [abynim/UserFlows.sketchplugin#172]
Hi! 
Every time I click create link (cmd+shift+M) it appears this label (image attached).
<img width="497" alt="Captura de pantalla 2020-04-03 a las 9 26 19" src="https://user-images.githubusercontent.com/63093324/78335050-31872380-758d-11ea-83af-a8a1e91d5e86.png">

Can someone help me?
Thanks

**Comment by abynim** [comment]
This happens if you've previously chosen to hide connections. Try running `Plugins > User Flows > Show or Redraw Connections` and you should see the links being drawn instead of this message.

**Comment by gayco** [comment]
> This happens if you've previously chosen to hide connections. Try running `Plugins > User Flows > Show or Redraw Connections` and you should see the links being drawn instead of this message.

Wow...you saved my life!! thank you so much!
