### ISSUE TITLE
Generate Flow Diagram Bug

### ISSUE THREAD

**Issue by boydwork** [abynim/UserFlows.sketchplugin#177]
As the sketch version is upgraded, when you click the Generate Flow Diagram menu, the artboard is created by cutting the width of the artboard.

**Comment by abynim** [comment]
@boydwork which version of Sketch are you using? Also, does the flow contain links created via the plugin or Sketch prototyping links?

**Comment by boydwork** [comment]
@abynim 
It is currently version 71.2. And it doesn't contain the prototype link you mentioned.
This case seems to occur from version 70.6 or later.

When the dialgram was created, the artboard was created because the horizontal size of the artboard was correctly aligned, but the sketch was updated and it was not created properly.

I'm working on design in Korea. The UserFlows plugin you developed is really useful and very well used.
thank you.

**Comment by abynim** [comment]
@boydwork thanks for the details. I can reproduce it. Will check what's going on 👍🏽

**Comment by abynim** [comment]
@boydwork can you please try installing the update from the branch with fixes and tell me if it's working for you? Just want to confirm before merging.

https://github.com/abynim/UserFlows/archive/refs/heads/sketch-72-fixes.zip

**Comment by boydwork** [comment]
@abynim I just installed the improved plugin you mentioned and it has confirmed that it works very well. thank you.

**Comment by abynim** [comment]
@boydwork thanks for the confirmation, and also for reporting the issue 🙏🏽
