### ISSUE TITLE
Can't generate flow diagram

### ISSUE THREAD

**Issue by Beatriz215** [abynim/UserFlows.sketchplugin#179]
Used with Sketch 54.1

I have linked some screens and when I'm trying to "Generate Flow diagram" it does not generate the flow and I can't see the page "_flows" on my pages list. 

Can you help-me please?
@

**Comment by abynim** [comment]
@Beatriz215 I will check tomorrow since I need to download the older version. Meanwhile, if possible, could you please check if there is anything showing up in the logs when you try to generate a flow? 

You can open Console.app from Applications/Utilities and filter the logs by "Sketch". Then switch over to Sketch and try the command again, and let me know if you see anything in Console.app. Thanks!

**Comment by Beatriz215** [comment]
@abynim Thanks for your quick reply.
Please let me know if the prints bellow is what you need:

![Screenshot 2021-05-12 at 16 00 15](https://user-images.githubusercontent.com/29485846/117997831-40690980-b33b-11eb-87cd-b349e2fcb3db.png)
![Screenshot 2021-05-12 at 15 59 08](https://user-images.githubusercontent.com/29485846/117997821-3e06af80-b33b-11eb-997d-15dcc47334bb.png)

**Comment by abynim** [comment]
@Beatriz215 This is weird! Which version of macOS are you running? And can you please confirm if your Sketch app is inside the Applications folder?

Also, was this working before and stopped working recently? Trying to understand what might have changed, if it was working before.

Thanks for helping debug this 🙏🏽

**Comment by Beatriz215** [comment]
@abynim 

I'm running macOS Catalina version 10.15.4

I just checked and my Sketch app was not inside Applications folder. I just moved Sketch app to this folder and I tried again generate user flow but the issue still remains.

I've tried and installed this plugin today for the first time.

Thanks for your time again.

**Comment by abynim** [comment]
From the error it looks like a permissions issue (it seems you're not able to access the system cache folder). After moving Sketch to Applications folder, can you please try restarting your Mac? Please let me know if you still see the same issue in Console.app after restarting.

**Comment by Beatriz215** [comment]
@abynim I've noticed that when I trying to generate user flow by clicking it, all links (Arrows) disappears from the screens.

I've restarted my Mac and the issue remains:

<img width="997" alt="Screenshot 2021-05-13 at 09 43 17" src="https://user-images.githubusercontent.com/29485846/118101853-f7af6000-b3cf-11eb-9673-057e5ff5ee92.png">

**Comment by abynim** [comment]
@Beatriz215 this is so strange! Can you please try using an older version of the plugin from here: https://github.com/abynim/UserFlows/archive/f54a597946371b956f2efb7585ae7912cd1c5a0d.zip

Maybe I broke something for Catalina when I updated the plugin recently. Please let me know. Thanks 🙏🏽

**Comment by Beatriz215** [comment]
@abynim I've closed my sketch app and I noticed that I had a missing update
After updating, I had to update the plugin as well  and now I'm able to generate the user flow!

Thanks for all your support, this plugin gonna change my life 👏 haha
