### ISSUE TITLE
Sketch 79 - Flow diagram creation does not work

### ISSUE THREAD

**Issue by kamiyarsanau** [abynim/UserFlows.sketchplugin#181]
MOJavaScriptException: Error: An Obj-C exception occurred.
[native code]
generateFlowWithSettings script.js:1642:35
generateFlow script.js:1480:29

Error shown after clicking "Generate flow"

**Comment by kamiyarsanau** [comment]
+1

**Comment by abynim** [comment]
Should be fixed in v 2.3.9. Please test if you get a chance. Thanks!
