### ISSUE TITLE
Settings dialogue doesn't open

### ISSUE THREAD

**Issue by ghost** [abynim/UserFlows.sketchplugin#182]
When I go to Plugins > User Flows > Settings..., the Settings dialogue window doesn't open.

Keyboard Shortcuts... and Language... both work OK.

Weird

Thanks
Tim

Sketch 79.1
macOS 12.0.1

**Comment by kamiyarsanau** [comment]
+1

**Comment by abynim** [comment]
Should be fixed in v 2.3.9. Please test if you get a chance. Thanks!
