### ISSUE TITLE
Plugin broken

### ISSUE THREAD

**Issue by ghost** [abynim/UserFlows.sketchplugin#184]
Hi,

I'm guessing you're not maintaining this plugin anymore? It seems completely broken now. When I try and show or redraw connections it creates a whole bunch of new flow arrows not in a folder and doesn't remove any of the old ones. It's pretty close to unusable now sadly.

**Comment by abynim** [comment]
Should be fixed in v 2.3.9. Please test if you get a chance. Thanks!

Sorry for the delay in fixing the issues. I'm struggling with burnout and couldn't find time to work on the plugin 😔 Thanks for being so patient.
