### ISSUE TITLE
If this Plugin is abandoned, Please say so.

### ISSUE THREAD

**Issue by MamaMac** [abynim/UserFlows.sketchplugin#186]
This is a great plugin - there isn't one like it anywhere. If it is no longer being maintained, please say so.

**Comment by abynim** [comment]
Sorry for the delay in fixing all the issues. I'm struggling with burnout and couldn't find time to work on the plugin 😔 Thanks for being so patient.

**Comment by miltontsai** [comment]
@abynim Thank you so much for updating this wonderful plug-in.    

This is by far the best plug-in for making User Flow document.  I'm having difficulty on alternative ones anywhere.  And this is the major reason that I kept using Sketch and not migrate to Figma.  (It would be great to have this plug-in on Figma as well.)

Please consider this a paid plug-in, and I would very much like to pay for it.
