### ISSUE TITLE
Generate Flow Diagram breaking for me

### ISSUE THREAD

**Issue by JasonOber** [abynim/UserFlows.sketchplugin#19]
Hi there!

Really lovely plugin. So, so simple to set up and use. It worked well at first, but on a new project I made from scratch it broke a little. I'm confused and could use some help.

Here is a screenshot of how my flow is set up currently:

![mae enrollment user flow dec 7](https://cloud.githubusercontent.com/assets/24442870/20988071/ad2c68d4-bc94-11e6-874c-c4b03e51aeaa.png)

Here is the result I'm getting:

![test](https://cloud.githubusercontent.com/assets/24442870/20987956/3b9ab4b4-bc94-11e6-9d27-8ee0bde2a53e.png)

I've tried doing different connections and having things on conditionals vs not on conditionals and still getting wonky results.

It worked well on a separate project:

![dkr enrollment edit](https://cloud.githubusercontent.com/assets/24442870/20988182/517f559a-bc95-11e6-8963-413d9c906c3b.png)

What am I missing?

Thanks so much!
Jason

**Comment by abynim** [comment]
@JasonOber could you please confirm that the `Start from` value has been set to your `start` artboard in the Generate Flow dialog? It looks like the flow is not being generated from the correct artboard.
![generate_flow](https://cloud.githubusercontent.com/assets/7082849/20994179/df858cb2-bd29-11e6-9c4f-e1da4cfeba62.png)

**Comment by JasonOber** [comment]
Yep! Here's what I can see as options, and the result I showed above was set to the "Start" board.

<img width="1057" alt="screen shot 2016-12-08 at 7 01 35 am" src="https://cloud.githubusercontent.com/assets/24442870/21010928/57bd09d2-bd14-11e6-836d-5bc7e123dab5.png">

PS - Beautiful baby in your pic. Congrats. =)

**Comment by abynim** [comment]
Thanks @JasonOber :) 
Wow, that's very strange behavior. Would you be able to send me a copy of this Sketch document to abynimbalkar [at] gmail [dot] com?

**Comment by JasonOber** [comment]
Right?! Just sent it. =)

**Comment by abynim** [comment]
@JasonOber thanks for sending over the Sketch doc. I've fixed this issue in version 2.0.1. Please reinstall the plugin and let me know if it works after that. 👍

**Comment by doefler** [comment]
Hey @abynim 
Thank you for an awesome plugin 😄 
I have a similar issue, I have linked 5 screens, but only 3 of them appear in the flow chart.
Just update the plugin and still same error.

**Comment by abynim** [comment]
@doefler is it possible to email me the Sketch doc? That's the easiest way to debug. abynimbalkar [at] gmail [dot] com. Thanks!

**Comment by JasonOber** [comment]
Seems to be fixed! Thanks!
