### ISSUE TITLE
Preferences > Plugins shows Version 2.3.9 Available

### ISSUE THREAD

**Issue by GitPhorus** [abynim/UserFlows.sketchplugin#191]
Sketch Version 71.2 (115329).  In Preferences > Plugins it shows an update to Version 2.3.9 Available.  After uninstalling and reinstalling User Flows the notification returns.

<img width="519" alt="Screen Shot 2022-04-13 at 1 18 26 PM" src="https://user-images.githubusercontent.com/4356303/163266961-1c6c5b25-ff37-4c49-9259-59197692909d.png">
 
A result of not being able to update is the persistent notification in the Sketch interface, which is a little distracting.

<img width="197" alt="Screen Shot 2022-04-13 at 1 46 40 PM" src="https://user-images.githubusercontent.com/4356303/163267839-c7f0aa0f-838e-44ce-92a7-6b96071ec2a2.png">

**Comment by abynim** [comment]
🤦🏻‍♂️ This is what happens when I try to publish an update at 2am! I've changed the version now, so updating one last time should fix it. Thanks for reporting!

**Comment by GitPhorus** [comment]
Thank you for fixing and for this plug-in!
