### ISSUE TITLE
How can I set quickly flow arrow border thickness?

### ISSUE THREAD

**Issue by gainnsopro** [abynim/UserFlows.sketchplugin#20]
I want to change default arrow border 3 to 7. Can I quickly change it? Or Do I have to separately choose layer of flow arrow?
Great works, thanks for this plugin.

**Comment by gainnsopro** [comment]
I want to change default arrow border 3 to 7. Can I quickly change it? Or Do I have to separately choose layer of flow arrow?

**Comment by abynim** [comment]
You can change the border thickness in the plugin's source here: 
https://github.com/abynim/UserFlows/blob/v2/UserFlows.sketchplugin/Contents/Sketch/script.js#L858
Change `setThickness(3*exportScale)` to `setThickness(7*exportScale)`

You might then also want to make the arrow larger. Do that here: 
https://github.com/abynim/UserFlows/blob/v2/UserFlows.sketchplugin/Contents/Sketch/script.js#L863

**Comment by edwardsdesign** [comment]
How about adding line thickness and arrow size to the User Flow settings screen?

**Comment by gainnsopro** [comment]
Thanks @abynim  I also agree with @edwardsdesign At first, I searched user flow settings screen.

**Comment by abynim** [comment]
Added a setting for this in version 2.0.1. Please reinstall the plugin to test 👍

**Comment by edwardsdesign** [comment]
The settings appear to be working as expected. I was able to change the color and stroke size through the new settings feature.

Tested on macOS Sierra 10.12.1 (16B2555) and Sketch 41.2 (35397)
