### ISSUE TITLE
flows 2 doesn´t work on OS Sierra

### ISSUE THREAD

**Issue by operasghost** [abynim/UserFlows.sketchplugin#23]
**# Description**

Flows 2 doesn´t generate the flow diagrams when I try to do it. It simply does´nt do nothing on sketch Version 41.2 (35397). Even after I quit sketch, instal it and restart the computer.

**Comment by abynim** [comment]
@operasghost could you possibly record a quick screencast of this behavior? I have the same configuration and it works as expected, so some more details would be useful in reproducing the issue.

**Comment by ctwhome** [comment]
It does't work for me neither. Version Sketch 41.2 (35397) OS Sierra. Just installed and calling the menu Generate Flow.... it does not do anything

**Comment by ctwhome** [comment]
Ah, ok so... if you install it from sketch toolbox I does not work. Download it from the webpage and install it with double click on the plugin. Then you get the latest version that works.

**Comment by abynim** [comment]
Yes, Sketch Toolbox is linking to an older version of the plugin. Thanks for reporting back with the solution @ctwhome.

**Comment by operasghost** [comment]
That´s what I did. But I found the problem. You can create the flows but only if you use the shortcut. If you go to the plugin bla, bla,.. menu it won’t work.

**Comment by operasghost** [comment]
Thank you for answering Nimbalkar

**Comment by abynim** [comment]
Glad it's working for you as well @operasghost 👍
