### ISSUE TITLE
Hide connections doesn't hide conditions

### ISSUE THREAD

**Issue by theiwaz** [abynim/UserFlows.sketchplugin#27]
I hide the connections before exporting to Invision, that works fine though my conditions aren't hidden and are uploaded to invision. Would be nice to have those hidden as well, saves me having to delete them in Invision afterwards.

**Comment by abynim** [comment]
Great point @theiwaz! Hiding condition artboards may not be possible without losing the information they contain. To prevent the artboard from syncing to InVision you can add a `-` prefix to the artboard name. In the next update I will make this the default way of naming condition artboards. Thanks for the feedback!

**Comment by abynim** [comment]
v2.0.2 adds a `-` prefix and suffix to Condition artboards to exclude them from syncing with InVision and FramerJS.

**Comment by theiwaz** [comment]
Super!!
