### ISSUE TITLE
Shortcut for Define Links (Create Link?) not working / present.

### ISSUE THREAD

**Issue by erutan** [abynim/UserFlows.sketchplugin#29]
In both 2.0 and 2.0.1 I don't have the `cmd shift k` shortcut appear in the menu, and there's no plugins with conflicting key combinations (unless there's something really hidden).

It gets rather tedious having to add things via menu.

<img width="311" alt="screen shot 2016-12-15 at 4 13 04 pm" src="https://cloud.githubusercontent.com/assets/199861/21247035/6f0456ae-c2e1-11e6-865a-a3f1a1e479cd.png">

**Comment by abynim** [comment]
This is most definitely caused by another plugin taking up the shortcut. Could you try setting a different shortcut via the `Keyboard Shortcuts` option and let me know if it works?

**Comment by brandtnew** [comment]
I have the same (?) problem and fixed it. Here's what I saw in the Menu. Installed it via SketchToolBox. Now I've uninstalled it via the SketchToolBox and installed it as instructed via the .sketchplugin file which you can download on https://abynim.github.io/UserFlows/. 

<img width="486" alt="screenshot 2016-12-16 16 38 31" src="https://cloud.githubusercontent.com/assets/21058715/21268242/1f5e6658-c3ae-11e6-8216-0573650be11f.png">

**Comment by erutan** [comment]
@brandtnew I didn't install via SketchToolBox (I like the idea, find it lacking in practice). I'll uninstall / reinstall and try again.

**Comment by abynim** [comment]
@brandtnew the version installed via SketchToolbox is the old version of UserFlows. To get the latest version (v2) please download it from the homepage https://abynim.github.io/UserFlows/

**Comment by erutan** [comment]
No other sketch plugins use the cmd shift k, but under system preferences > keyboard > shortcuts > application shortcuts Sketch itself has that set as a "Create Shared Style". Setting it to some other keyboard shortcurts work fine and shows up in the menu UI.

That may have been something I did a long time ago and forgot about since it doesn't seem to conflict for most.

**Comment by abynim** [comment]
Thanks for reporting back with the solution @erutan
