### ISSUE TITLE
Allow for more if/else statements when creating conditions?

### ISSUE THREAD

**Issue by erutan** [abynim/UserFlows.sketchplugin#30]
I have one flow where there's 5 device centric screens - as is I have to create the conditional box with one if else, then edit to add an option, edit again, edit again, etc. Being able to spawn more inputs on the initial creation would be appreciated. :)

**Comment by abynim** [comment]
v2.0.2 includes an option to `Save + Add` when adding/editing conditions. This lets you add another condition without having to run the plugin command again.

**Comment by erutan** [comment]
Thanks!
