### ISSUE TITLE
Incorrect starting point

### ISSUE THREAD

**Issue by parkerkuncl** [abynim/UserFlows.sketchplugin#32]
I have a larger layer that hangs off the artboard. I'm trying to have a flow arrow go from one artboard to another by selecting this layer. The RED arrow is pointing to the incorrect start as its overhanging the wrong artboard. It should be where the green arrow is, and not the hidden layer. Make sense?

![plugin fail](https://cloud.githubusercontent.com/assets/24660791/21331351/d0e3c2fc-c5f6-11e6-8f44-9a161b42b7a2.png)

**Comment by abynim** [comment]
Fixed in v 2.0.2
