### ISSUE TITLE
Feature request: Keep connections when pasting page to different file

### ISSUE THREAD

**Issue by skrzyszewski** [abynim/UserFlows.sketchplugin#39]
It would be quite nice if connections where kept while pasting whole page to a different document. Currently they're being transferred and visible, only until a 'Redraw Connections' keyboard shortcut is being pressed, then they disappear.

The reason this could be useful, is when you work with multiple designers on one project and trying to follow a git-flow like approach with separate files for features and one master file. This involves manual merging of documents, hence pasting artboards with already made connections.

Do you think this is possible to achieve?

PS Love the plugin!

**Comment by abynim** [comment]
@skrzyszewski v2.0.3 fixes this issue. Links should now work when you duplicate a page or artboard. With old documents, please run a `Redraw Connections` command once to update the data model before trying to copy-paste the page.

**Comment by skrzyszewski** [comment]
Works like a charm!
