### ISSUE TITLE
in certain cases connecting to a "duplicated" artboard doesn't work

### ISSUE THREAD

**Issue by Charimon** [abynim/UserFlows.sketchplugin#40]
If you try to connect to a **duplicated** artboard after a connection has been made to "original" artboard, the new connection will be made to the **original** artboard also.

Steps to reproduce:

1. Create Artboard (Let's call it **A1**, you don't actually have to rename it)
1. Create another Artboard  (Let's call it **A2**, you don't actually have to rename it)
1. Add 2 shapes (say Rectangle **R1** and **R2**) to **A1**
1. Create Connection from **R1** to **A2**
1. **Duplicate** Artboard **A2** to create Artboard **A2_dup**
1. Create Connection from **R2** to **A2_dup**

You should now see a connection made from **R2** to **A2** instead of **R2** to **A2_dup**
This only happens after you duplicate something with an existing connection. If you duplicate before any connections are made, everything is fine. So it's an edge case, but a relatively common one.

![image](https://cloud.githubusercontent.com/assets/1023405/22004080/a11d55ec-dc0d-11e6-9a8c-e8a461170466.png)

**Comment by abynim** [comment]
Please update to v2.0.4 which should fix this issue. Please test and let me know if it doesn't! Thanks for reporting btw 👍

**Comment by Charimon** [comment]
seems to be working now, thanks for fixing it so quickly. 👍🏻
