### ISSUE TITLE
New link connected to one artboard

### ISSUE THREAD

**Issue by work-leonid** [abynim/UserFlows.sketchplugin#41]
Hi! After updating User flows 2.0.3 (from 2.0.0) links don't work http://take.ms/i5m4K
Sketch 41.2 (35397), MacOS Sierra 10.12 (16A323), User Flows 2.0.3

**Comment by abynim** [comment]
This happens when the artboard you're linking to is a duplicate of another artboard. The bug was introduced in the latest update and Im working on a fix. Let's keep track of the bug in issue #40
