### ISSUE TITLE
How to set which side of the hit target the line will draw from

### ISSUE THREAD

**Issue by richardquay** [abynim/UserFlows.sketchplugin#44]
Right now every time I create a connection, the line is drawn from the right of the touch box. I looked around and can't find a way to set which side it is drawn from.

thanks!

**Comment by abynim** [comment]
The starting point of a connection stroke is determined by the position of the destination artboard in relation to the link layer. It could start from the top, right or bottom of the link layer, but not from the left (to avoid clashing with connections coming into the link's parent artboard). This happens automatically and there is no way to manually set the start point – not yet!
![connection-magnets](https://cloud.githubusercontent.com/assets/7082849/22171368/57f067c0-dfc7-11e6-81cb-3548e93e1256.png)

**Comment by richardquay** [comment]
thanks! Do you have a planned feature to allow the user to manually set the location?

**Comment by abynim** [comment]
Will try to include it in the next update 👍
