### ISSUE TITLE
Erased links reappearing

### ISSUE THREAD

**Issue by klv90** [abynim/UserFlows.sketchplugin#49]
Hello there. Nice work with the plugin. Really useful, i must admit it.
I have only one problem, and I don't know why...
Everytime i try to erase/remove a link, when I draw a new one, all the others that were drawn, reappear. And I end up with dozens of old links, all at once. It's like I can never erase them...
Any ideas ?
Thank you !

**Comment by abynim** [comment]
Thanks @klv90, glad you're finding it useful.
Deleting the connection lines will only remove them temporarily. The correct way to remove a link is to select the link layer and use the `Remove Link` command. Let me know if that works.

**Comment by klv90** [comment]
Thanks for your reply. 
I was trying that, but i was selecting both the source layer and the artboard. That was the problem.
Now it works perfect !!!
Thank you very much !
