### ISSUE TITLE
Removing an existing link

### ISSUE THREAD

**Issue by kungquest** [abynim/UserFlows.sketchplugin#50]
Hi @abynim , 

Loving your work here. You can't possible imagine how much designers/devs are crying with joy now. 

I noticed there was no instructions on 'Remove Links'. 
For example: I linked Button A to Artboard A, now I'm changing Button B to Artboard A. How can I go about doing so?

**Comment by kungquest** [comment]
Hi guys, I found it. It was under Plugins > Remove Links (or Cmd+Shift+U). Closing Issue.

**Comment by andrewmbacon** [comment]
This should really be in the documentation somewhere.

**Comment by abynim** [comment]
@andrewmbacon thanks for the feedback. I'll add it to the homepage 👍
