### ISSUE TITLE
Feature Request: Ability for custom page name

### ISSUE THREAD

**Issue by everydayslang** [abynim/UserFlows.sketchplugin#54]
Currently a page called _Flows is created. Which may or may not fit into someones naming system. You  can rename it, however when a new flow is created it won't respect the new name.

**Comment by abynim** [comment]
@everydayslang you can choose to generate a flow on any page you like, and the plugin will remember your choice.
![flowpage-name](https://cloud.githubusercontent.com/assets/7082849/23974658/52cae4f8-0a17-11e7-881c-c558201c4c8a.png)

**Comment by everydayslang** [comment]
Oh dang, there it is. Thanks for pointing that out.

Best,
Stephen
