### ISSUE TITLE
Install Sketchpacks Relay Integration

### ISSUE THREAD

**Issue by adamkirkwood** [abynim/UserFlows.sketchplugin#55]
https://github.com/integration/sketchpacks-relay

**Comment by abynim** [comment]
@adamkirkwood Done for all my plugins 👍 
<img width="515" alt="sketchpacks-integrations" src="https://cloud.githubusercontent.com/assets/7082849/24181768/32f30482-0ee3-11e7-8b6f-f94d419483e2.png">
