### ISSUE TITLE
Change "Connections" group name for InVision Sync compatibility

### ISSUE THREAD

**Issue by matteodesanti** [abynim/UserFlows.sketchplugin#56]
I need to avoid that my connections are automatically published to InVision when i save the sketch document. 
The solution I suggest is to rename the `Connections` auto-generated group to `-Connections`
Or we could let the user to choose the group name in the settings panel.

**Comment by abynim** [comment]
Changed the auto-generated group name from `Connections` to `-Connections-` so it will be excluded from InVision and Framer. Thanks for the feedback!
