### ISSUE TITLE
Plugin does not work with Sketch 44

### ISSUE THREAD

**Issue by rajankinnek** [abynim/UserFlows.sketchplugin#79]
It will be great if you can fix. Thanks!

**Comment by abynim** [comment]
@rajankinnek what part of it is not working? Some details would be nice. Thanks!

**Comment by rajankinnek** [comment]
Thanks for the speedy reply. I do not see the connection lines though I get a notification that they have been drawn.

**Comment by abynim** [comment]
@rajankinnek Try `UserFlows` > `Show or Redraw Connections`, or use the shortcut `Cmd+Shift+9`. That should redraw the connections.

**Comment by rajankinnek** [comment]
Perfect. That fixed it! Thanks a bunch. You saved me a boatload of time!
