### ISSUE TITLE
Able to RESET/REMOVE all linked connections.. 

### ISSUE THREAD

**Issue by stefftabalong** [abynim/UserFlows.sketchplugin#81]
I was moving artboards around and connections was hidden and this happened.

<img width="369" alt="screen shot 2017-05-31 at 6 47 40 pm" src="https://cloud.githubusercontent.com/assets/13848412/26628735/ca825d2c-4631-11e7-815d-b7d61f7f3ee6.png">

I tried the redraw/hide connection does NOT work. I tried deleting them from the layers directly does not work as well. It removed them but when I linked another connection it will appear again. This has been a recurring issue.. I hope this will be solved

**Comment by abynim** [comment]
@stefftabalong are you able to share the document where this is happening? Please send it to abynimbalkar at gmail dot com. That will be the fastest way to debug the issue.

**Comment by abynim** [comment]
@stefftabalong a command to `Remove All Links` has been added in v2.0.7. Please update so you can use it the next time you're facing the same issue.
