### ISSUE TITLE
Setting Connectors to Middle of Artboard

### ISSUE THREAD

**Issue by maynardj20** [abynim/UserFlows.sketchplugin#88]
When connecting an object to an artboard, I would love the ability to choose where the connector connects with the artboard.  Currently, it connects at the top-left corner, but I would prefer it to point to the middle-left side.

Keep up the good work!

**Comment by cetm0109** [comment]
The latest version (with connectors connecting to the middle of artboards) has broken my documents as I was using the space available between artboards for notes.
Is there a way to be able to select between the top-left corner AND the middle for those of use who already had a workflow in place?
Thank you!

**Comment by abynim** [comment]
@cetm0109 this has been requested in another issue so it's on the list. 

If it is disrupting your work, maybe for now you can switch back to the version before this change was added: https://github.com/abynim/UserFlows/archive/1d15fef1a7dd00eed51a9e1d01f3b85f014b4f92.zip

I'll update this issue once I've added the option to choose between top-left and middle 👍

**Comment by cetm0109** [comment]
@abynim Didn't need to revert to an older version. The latest release fixed my issue AND addd more options! 
This is great!
Thank you.
