### ISSUE TITLE
Scale down @2x exported artboard

### ISSUE THREAD

**Issue by ixley** [abynim/UserFlows.sketchplugin#89]
When generating the bitmapped artboards for the Flow Diagram, the 2x option is great, but it would be even nicer if it was also scaled down to 50%. This way the bitmaps retain detail for hi-res display but zoom to the appropriate 100% scale.

Thanks for the great plugin - keep up the good work!

**Comment by abynim** [comment]
@ixley Thanks for the feedback. This has been added as a setting in v2.0.7. Please update to try it out 👍
